# @package _global_
model:
  # Model architecture
  patch_size: 256
  levels: [8, 8, 8, 5, 5, 5] # FSQ levels

  # Encoder configuration
  encoder_config:
    hidden_dims: [512, 512, 512]
    dropout: 0.1
    norm_type: layer
    use_residual: false
    use_gelu_gating: false
    activation: "relu"

  # Decoder configuration
  decoder_config:
    hidden_dims: [512, 512, 512]
    dropout: 0.1
    norm_type: layer
    use_residual: false
    use_gelu_gating: false
    activation: "relu"

  # Conditioning parameters
  use_conditioning: false
  condition_dim: 16
  max_sampling_rate: 1000.0
